### ISSUE TITLE
The performance in WebXR has dropped by half

### ISSUE THREAD

**Issue by yeungeek** [Igalia/wolvic-chromium#111] opened 2024-07-25 08:23 UTC
After using the latest code, WebXR performance drops from 90HZ to 45HZ after loading this page(https://immersive-web.github.io/webxr-samples/teleportation.html). 
However, it's normal under the Gecko engine. What information is needed for troubleshooting? @svillar

@zakharvoit
Not the same as #103.

Use the perfetto to track, `com.igalia.wolvic:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0 `cost much time. 

![image](https://github.com/user-attachments/assets/321f9a33-9363-4d98-a17b-214b702646de)

`CrRendererMain` Thread:
![image](https://github.com/user-attachments/assets/547f688f-54ef-4027-a451-339cd1ed8f20)

**Comment by svillar** [comment] 2024-07-29 07:56
have you seen the same in any other experience?

**Comment by yeungeek** [comment] 2024-07-30 13:19
The above case was tested based on Rokid devices (Qualcomm Snapdragon XR2+ Gen 1).
Later, we also conducted tests on Pico4, and the frame rate also dropped from 90Hz to 50Hz.

Is there any way to pinpoint the specific issue or provide relevant logs?

Thanks!

**Comment by svillar** [comment] 2024-07-30 16:10
what I am trying to understand is when that performance drop happened. Which version does provide 90FPS and which one 45FPS? Are you comparing different chromium versions? Or comparing the chromium version with the gecko one?

**Comment by yeungeek** [comment] 2024-08-01 06:57
We compared the Chromium and Gecko versions. Upon entering the WebXR site, we noticed a difference in GPU usage time.
Chromium perfetto trace, Cost `10ms`:
<img width="658" alt="chrome" src="https://github.com/user-attachments/assets/bc147184-de7b-4897-83ae-93d15520487d">

Gecko perfetto trace, Cost `6ms`:
<img width="524" alt="gecko" src="https://github.com/user-attachments/assets/ec32c252-b4a2-4d83-a5cb-510d775d06c6">

The GPU usage time exactly corresponds with the frame rate.
Does this help in analyzing the problem?

**Comment by svillar** [comment] 2024-08-01 07:26
Wow that's surprising because we've seen exactly the opposite, chromium providing 2x and even 3x the FPS compared to gecko. We'll check that

**Comment by yeungeek** [comment] 2024-08-01 07:35
We were surprised and thought it might be a code issue, but we only compiled different browser kernel versions. Could there be different configurations, or is there a discrepancy in the Chromium version we compiled?

The compilation of Chromium followed：https://github.com/Igalia/wolvic/blob/main/CHROMIUM.md

What VR device was your testing based on?

We will test on other VR devices as well.

**Comment by yeungeek** [comment] 2024-08-01 07:38
> Wow that's surprising because we've seen exactly the opposite, chromium providing 2x and even 3x the FPS compared to gecko. We'll check that

To add, the frame rate is normal when first entering the application, but it only drops after entering the WebXR site.

**Comment by svillar** [comment] 2024-08-01 07:55
> We were surprised and thought it might be a code issue, but we only compiled different browser kernel versions. Could there be different configurations, or is there a discrepancy in the Chromium version we compiled?
> 
> The compilation of Chromium followed：https://github.com/Igalia/wolvic/blob/main/CHROMIUM.md
> 
> What VR device was your testing based on?
> 
> We will test on other VR devices as well.

Are you sure you have built a release version of chromium? If you build chromium debug the performance is much worst due to the extra amount of code it executes and the lack of compiler optimizations.

Also can you reproduce it with the packages we released?

I've just tried the experience on a pico4 and I'm getting a constant 72PFS which is the maximum given the 72Hz refresh rate of the device

**Comment by yeungeek** [comment] 2024-08-01 08:28
I’m trying to determine if it’s a debug version issue. That might be the cause. We will recompile and test the release version again. Thanks!

**Comment by yeungeek** [comment] 2024-08-03 07:49
After switching to the release version, the frame rate improved to an average of 80FPS. The difference between debug and release versions is very noticeable. Thanks to @svillar  for the support.  But Gecko can reach 90fps，We will further investigate their differences. 
We also look forward to the stable release of Wolvic Chromium soon.

**Comment by svillar** [comment] 2024-08-03 18:03
OK closing now

**Closed as completed by svillar** 2024-08-03 18:03 UTC
